# Generated by Django 3.1.1 on 2020-09-26 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='postd',
            managers=[
            ],
        ),
    ]
